### PR TITLE
Refactor: update React imports #5

### PR DESCRIPTION
**Pull request by Jwright707**
Update any instance of `import React from 'react'` to `import * as React from 'react'`.

### CODE REVIEW

**Review by kenfeliciano — CHANGES_REQUESTED** [review]
This is a great learning experience for me. I hope it is for you too! 

I will research what this .idea stuff is. It looks like you have added `.idea/` in `.gitignore` but git didn't care and added a few files in the .idea/ directory to the PR. The changes I wanted to do look perfect 👍! Can you resubmit the PR without the .idea/ files and without the change to `.gitignore` please? Perhaps it would be good to have that in there but since I haven't heard of it, I'll keep it out for now.

I have no `CONTRIBUTING.md` file in this repo yet. I imagine it should include something about not including these types of files in a PR. Still new to me though.

**Comment by Jwright707** [comment]
Hey @kenfeliciano of course!

**Comment by Jwright707** [comment]
Just removed the .idea from the repo and the .gitignore. I believe those changes will be in this PR. I can also try to close this PR and reopen if you like. 😃

**Comment by kenfeliciano** [comment]
It looks like the changes will come through as expected. I'm going to go with it like this and see how it goes. Thank you @Jwright707 for working on this. I'm glad you did!

**Comment by kenfeliciano** [comment]
It worked perfectly. Thanks again @Jwright707!

**Pull request merged**
